name: flutter_prince_of_versions
description: Library for easier versioning of your applications. You can check for updates from a remote server, Google Play or App Store.
version: 2.2.3
repository: https://github.com/infinum/flutter-prince-of-versions
homepage: https://github.com/infinum/flutter-prince-of-versions

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.infinum.flutter_prince_of_versions
        pluginClass: FlutterPrinceOfVersionsPlugin
      ios:
        pluginClass: FlutterPrinceOfVersionsPlugin
