name: flutter_prince_of_versions
description: Library for easier versioning of your applications. You can check for updates from a remote server, Google Play or App Store.
version: 2.0.1
repository: https://github.com/infinum/flutter-prince-of-versions
homepage: https://github.com/infinum/flutter-prince-of-versions

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_prince_of_versions
        pluginClass: FlutterPrinceOfVersionsPlugin
      ios:
        pluginClass: FlutterPrinceOfVersionsPlugin
